### ISSUE TITLE
When getting a source location during macro resolution, everything is optional

### ISSUE THREAD

**Issue by grynspan** [apple/swift-syntax#1309] opened 2023-02-02 22:52 UTC
### Description

When using a macro context to get a source location during macro resolution, the source location itself is optional, and so is every property in the structure. That seems a bit much.

I'd suggest making just the source location optional (since you could pass an `Expr` from elsewhere) and then all the properties can be non-optional. I might also suggest having a `macroSourceLocation` property that's non-optional, since you presumably always know the macro's location!

**Comment by ahoppen** [comment] 2023-02-02 23:00
rdar://104979208

**Comment by ahoppen** [comment] 2023-06-21 10:11
I think this is a duplicate of https://github.com/apple/swift-syntax/issues/1525, which has been fixed.

**Closed by ahoppen** 2023-06-21 10:11 UTC
Labels: bug

**Comment by grynspan** [comment] 2023-06-21 20:29
Agreed!
