### ISSUE TITLE
Round-trip failure with malformed struct

### ISSUE THREAD

**Issue by DougGregor** [apple/swift-syntax#678] opened 2022-08-31 23:50 UTC
### Issue Kind

Round-Trip Failure

### Source Code

```swift
struct n#if@
```

**Comment by ahoppen** [comment] 2022-09-01 10:14
rdar://99430621

**Comment by MEnnabah** [comment] 2022-09-05 17:16
Couldn't reproduce this as a round-trip on main (`741b5c0`). I've added a test to cover this case #711.

**Comment by CodaFi** [comment] 2022-09-06 06:08
Resolved by the merge of #711

**Closed by CodaFi** 2022-09-06 06:08 UTC
Labels: bug, good first issue, SwiftParser
