### ISSUE TITLE
Inconsistency in Parsing: `SequenceExprSyntax` vs `InfixOperatorExprSyntax` in `SwiftSyntax` and Compile

### ISSUE THREAD

**Issue by Matejkob** [apple/swift-syntax#2152] opened 2023-09-05 06:02 UTC
### Issue Kind

I Don’t Know

### Source Code

```swift
func testMacroWithInfixOperatorExpr() {
  final class Visitor: SyntaxRewriter {
    override func visit(
      _ node: InfixOperatorExprSyntax
    ) -> ExprSyntax {
      ExprSyntax(node.with(\.rightOperand, "2"))
    }
  }
  struct Macro: ExpressionMacro {
    static func expansion(
      of node: some FreestandingMacroExpansionSyntax,
      in context: some MacroExpansionContext
    ) throws -> ExprSyntax {
      let visitor = Visitor()
      let rewritedNode = visitor.rewrite(node)

      return rewritedNode.asProtocol(FreestandingMacroExpansionSyntax.self)?.argumentList.first?.expression ?? ""
    }
  }

  assertMacroExpansion(
    """
    #MyMacro(x + 1)
    """,
    expandedSource: """
    x + 2
    """,
    macros: ["MyMacro": Macro.self]
  )
}
```

### Description

If I'm not mistaken the expression `x + 1` is parsed differently by `SwiftSyntax` and the Swift compiler. In `SwiftSyntax`, it is represented as a `SequenceExprSyntax`, while the compiler parses it as an `InfixOperatorExprSyntax`.

Here is how the compiler expands the above macro into the following Swift expression:
```swift
x + 1
```
![Screenshot](https://github.com/apple/swift-syntax/assets/44930823/ed47b562-f29e-4555-a80b-5718b6a886b6)

However, when attempting to test this macro using `SwiftSyntax`'s `MacroSystem`, it fails to expand in the same manner as the compiler.

**Comment by ahoppen** [comment] 2023-09-05 06:44
Tracked in Apple’s issue tracker as rdar://114963932

**Comment by ahoppen** [comment] 2023-09-05 20:53
This is a duplicate of https://github.com/apple/swift-syntax/issues/2128. Closing so we are only tracking the issue once.

**Closed by ahoppen** 2023-09-05 20:53 UTC
Labels: bug, SwiftParser

**Comment by ahoppen** [comment] 2023-09-06 18:08
Not a problem at all, please file issues. I’ve got the better overview of which other open issues there are and am always happy to close ones that we are already tracking.
