### ISSUE TITLE
There should be a syntax trait covering `genericParameterClause` and `genericWhereClause`

### ISSUE THREAD

**Issue by grynspan** [apple/swift-syntax#1810] opened 2023-06-18 18:01 UTC
### Description

There should be a syntax trait protocol covering `genericParameterClause` and `genericWhereClause` for the syntax types that have one or both of these properties. (IMHO a single protocol is the appropriate granularity rather than one for each property.)

**Comment by ahoppen** [comment] 2023-06-18 18:59
Tracked in Apple’s issue tracker as rdar://110973434

**Comment by Matejkob** [comment] 2023-07-10 10:53
If nobody's working on this issue I'd like to try solve it

**Comment by Matejkob** [comment] 2023-07-10 10:54
@ahoppen That was a misclick; sorry XD. Can you reassign it?

**Comment by grynspan** [comment] 2023-07-10 13:00
Thanks for taking a look!

**Comment by Matejkob** [comment] 2023-07-12 14:21
Just to clarify, are we focusing only on the creation of a syntax trait, as shown below:
```swift
Trait(
  traitName: "WithGenericParameterAndWhereClause",
  documentation: """
    Represents a syntax node that has an optional `genericParameterClause` and `genericWhereClause` children.

    For example, functions or types like class or struct can be generic and have a where clause in Swift.
    """,
  children: [
    Child(name: "GenericParameterClause", kind: .node(kind: .genericParameterClause), isOptional: true),
    Child(name: "GenericWhereClause", kind: .node(kind: .genericWhereClause), isOptional: true)
  ]
),
```
and then extending each declaration node, with this trait, which has `genericParameterClause` and `genericWhereClause` children? We don't need to apply this new trait in the code currently, correct?

If my understanding of the issue is accurate, what is your opinion on the suggested trait name and its documentation?

**Comment by ahoppen** [comment] 2023-07-13 05:41
I would name it `WithGenericParameters`. 
 
Regarding documentation, I would write something like the following.

For the node
```
Syntax nodes that have generic parameters.

For example, functions or nominal types like `class` or `struct` can have generic parameters and have a generic where clause that restricts these generic parameters.
```

For `GenericParameterClause`: 
```
The parameter clause that defines the generic parameters.
```

For `GenericWhereClause`: 
```
A `where` clause that places additional constraints on generic parameters like `where Element: Hashable`.
```

And if you want to, I think it would make sense to add very similar comments to the `GenericParameterClause` and `GenericWhereClause` types.

**Comment by Matejkob** [comment] 2023-07-13 05:59
How about we also add a similar comment to all children nodes of kinds `GenericParameterClause` and `GenericWhereClause` in all declaration nodes?

**Comment by ahoppen** [comment] 2023-07-13 06:02
I was just about to suggest that. I was briefly considering whether we should automatically inherit the documentation from the trait but explicitly adding it to the children of the nodes seems like the better option to me.

**Comment by Matejkob** [comment] 2023-07-13 06:10
I've also been considering some sort of automation for this case. I'm unsure if inheritance would be the best approach. Perhaps it would be more efficient to centralize declaration documentation content in one location, and then inject it into each node using the Localizable feature or by assigning it to properties, or via some other pattern. Copying and pasting the same string to different nodes seems highly unproductive and could easily lead to inconsistencies if someone decides to modify the content of the documentation and forget to update it in all places.

**Comment by ahoppen** [comment] 2023-07-13 06:25
I thought about the same at first but then came to the conclusion that it’s good if we have the option to write slightly different documentation for each node. E.g. `where Element: Hashable` makes more sense for nominal type declarations and for function declarations `where Collection.Element: SomeProtocol`.

**Closed** 2023-07-13 17:27 UTC
Labels: enhancement, good first issue
